/**
 * AUTHOR: Anurag Pathak
 * LANGUAGE: Kotlin
 * GITHUB: https://github.com/AnuragThePathak
 */

// This is how to write document which can be generated by KDoc

fun main() {
    print("Hello World!")
}
